version: "3"
services:
  ui:
    build:
      context: ./ui/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - ui-node-modules:/workspace/ui/node_modules
      - ui-extensions:/root/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
  server:
    build:
      context: ./server/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - server-node-modules:/workspace/server/node_modules
      - server-extensions:/root/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  ui-node-modules:
  server-node-modules:
  ui-extensions:
  server-extensions:
